// Nama surah dalam Bahasa Indonesia dan Arab dengan harakat

export interface SurahName {
  id: number;
  arabic: string;
  latin: string;
  indonesia: string;
  arti: string;
  ayat: number;
  type: "Makkiyah" | "Madaniyah";
}

export const surahNames: SurahName[] = [
  { id: 1, arabic: "ٱلْفَاتِحَة", latin: "Al-Fatihah", indonesia: "Al-Fatihah", arti: "Pembukaan", ayat: 7, type: "Makkiyah" },
  { id: 2, arabic: "ٱلْبَقَرَة", latin: "Al-Baqarah", indonesia: "Al-Baqarah", arti: "Sapi", ayat: 286, type: "Madaniyah" },
  { id: 3, arabic: "آلِ عِمْرَان", latin: "Ali 'Imran", indonesia: "Ali 'Imran", arti: "Keluarga Imran", ayat: 200, type: "Madaniyah" },
  { id: 4, arabic: "ٱلنِّسَاء", latin: "An-Nisa", indonesia: "An-Nisa'", arti: "Wanita", ayat: 176, type: "Madaniyah" },
  { id: 5, arabic: "ٱلْمَائِدَة", latin: "Al-Ma'idah", indonesia: "Al-Ma'idah", arti: "Hidangan", ayat: 120, type: "Madaniyah" },
  { id: 6, arabic: "ٱلْأَنْعَام", latin: "Al-An'am", indonesia: "Al-An'am", arti: "Binatang Ternak", ayat: 165, type: "Makkiyah" },
  { id: 7, arabic: "ٱلْأَعْرَاف", latin: "Al-A'raf", indonesia: "Al-A'raf", arti: "Tempat Tertinggi", ayat: 206, type: "Makkiyah" },
  { id: 8, arabic: "ٱلْأَنفَال", latin: "Al-Anfal", indonesia: "Al-Anfal", arti: "Rampasan Perang", ayat: 75, type: "Madaniyah" },
  { id: 9, arabic: "ٱلتَّوْبَة", latin: "At-Taubah", indonesia: "At-Taubah", arti: "Pengampunan", ayat: 129, type: "Madaniyah" },
  { id: 10, arabic: "يُونُس", latin: "Yunus", indonesia: "Yunus", arti: "Nabi Yunus", ayat: 109, type: "Makkiyah" },
  { id: 11, arabic: "هُود", latin: "Hud", indonesia: "Hud", arti: "Nabi Hud", ayat: 123, type: "Makkiyah" },
  { id: 12, arabic: "يُوسُف", latin: "Yusuf", indonesia: "Yusuf", arti: "Nabi Yusuf", ayat: 111, type: "Makkiyah" },
  { id: 13, arabic: "ٱلرَّعْد", latin: "Ar-Ra'd", indonesia: "Ar-Ra'd", arti: "Guruh", ayat: 43, type: "Madaniyah" },
  { id: 14, arabic: "إِبْرَاهِيم", latin: "Ibrahim", indonesia: "Ibrahim", arti: "Nabi Ibrahim", ayat: 52, type: "Makkiyah" },
  { id: 15, arabic: "ٱلْحِجْر", latin: "Al-Hijr", indonesia: "Al-Hijr", arti: "Batu Gunung", ayat: 99, type: "Makkiyah" },
  { id: 16, arabic: "ٱلنَّحْل", latin: "An-Nahl", indonesia: "An-Nahl", arti: "Lebah", ayat: 128, type: "Makkiyah" },
  { id: 17, arabic: "ٱلْإِسْرَاء", latin: "Al-Isra", indonesia: "Al-Isra'", arti: "Perjalanan Malam", ayat: 111, type: "Makkiyah" },
  { id: 18, arabic: "ٱلْكَهْف", latin: "Al-Kahf", indonesia: "Al-Kahfi", arti: "Gua", ayat: 110, type: "Makkiyah" },
  { id: 19, arabic: "مَرْيَم", latin: "Maryam", indonesia: "Maryam", arti: "Maryam", ayat: 98, type: "Makkiyah" },
  { id: 20, arabic: "طه", latin: "Ta-Ha", indonesia: "Taha", arti: "Taha", ayat: 135, type: "Makkiyah" },
  { id: 21, arabic: "ٱلْأَنْبِيَاء", latin: "Al-Anbiya", indonesia: "Al-Anbiya'", arti: "Para Nabi", ayat: 112, type: "Makkiyah" },
  { id: 22, arabic: "ٱلْحَجّ", latin: "Al-Hajj", indonesia: "Al-Hajj", arti: "Haji", ayat: 78, type: "Madaniyah" },
  { id: 23, arabic: "ٱلْمُؤْمِنُون", latin: "Al-Mu'minun", indonesia: "Al-Mu'minun", arti: "Orang-orang Mukmin", ayat: 118, type: "Makkiyah" },
  { id: 24, arabic: "ٱلنُّور", latin: "An-Nur", indonesia: "An-Nur", arti: "Cahaya", ayat: 64, type: "Madaniyah" },
  { id: 25, arabic: "ٱلْفُرْقَان", latin: "Al-Furqan", indonesia: "Al-Furqan", arti: "Pembeda", ayat: 77, type: "Makkiyah" },
  { id: 26, arabic: "ٱلشُّعَرَاء", latin: "Ash-Shu'ara", indonesia: "Asy-Syu'ara'", arti: "Para Penyair", ayat: 227, type: "Makkiyah" },
  { id: 27, arabic: "ٱلنَّمْل", latin: "An-Naml", indonesia: "An-Naml", arti: "Semut", ayat: 93, type: "Makkiyah" },
  { id: 28, arabic: "ٱلْقَصَص", latin: "Al-Qasas", indonesia: "Al-Qasas", arti: "Kisah-kisah", ayat: 88, type: "Makkiyah" },
  { id: 29, arabic: "ٱلْعَنكَبُوت", latin: "Al-Ankabut", indonesia: "Al-'Ankabut", arti: "Laba-laba", ayat: 69, type: "Makkiyah" },
  { id: 30, arabic: "ٱلرُّوم", latin: "Ar-Rum", indonesia: "Ar-Rum", arti: "Romawi", ayat: 60, type: "Makkiyah" },
  { id: 31, arabic: "لُقْمَان", latin: "Luqman", indonesia: "Luqman", arti: "Luqman", ayat: 34, type: "Makkiyah" },
  { id: 32, arabic: "ٱلسَّجْدَة", latin: "As-Sajdah", indonesia: "As-Sajdah", arti: "Sujud", ayat: 30, type: "Makkiyah" },
  { id: 33, arabic: "ٱلْأَحْزَاب", latin: "Al-Ahzab", indonesia: "Al-Ahzab", arti: "Golongan-golongan", ayat: 73, type: "Madaniyah" },
  { id: 34, arabic: "سَبَأ", latin: "Saba", indonesia: "Saba'", arti: "Negeri Saba", ayat: 54, type: "Makkiyah" },
  { id: 35, arabic: "فَاطِر", latin: "Fatir", indonesia: "Fatir", arti: "Pencipta", ayat: 45, type: "Makkiyah" },
  { id: 36, arabic: "يسٓ", latin: "Ya-Sin", indonesia: "Yasin", arti: "Yasin", ayat: 83, type: "Makkiyah" },
  { id: 37, arabic: "ٱلصَّافَّات", latin: "As-Saffat", indonesia: "As-Saffat", arti: "Yang Berbaris", ayat: 182, type: "Makkiyah" },
  { id: 38, arabic: "صٓ", latin: "Sad", indonesia: "Sad", arti: "Sad", ayat: 88, type: "Makkiyah" },
  { id: 39, arabic: "ٱلزُّمَر", latin: "Az-Zumar", indonesia: "Az-Zumar", arti: "Rombongan", ayat: 75, type: "Makkiyah" },
  { id: 40, arabic: "غَافِر", latin: "Ghafir", indonesia: "Gafir", arti: "Pengampun", ayat: 85, type: "Makkiyah" },
  { id: 41, arabic: "فُصِّلَت", latin: "Fussilat", indonesia: "Fussilat", arti: "Yang Dijelaskan", ayat: 54, type: "Makkiyah" },
  { id: 42, arabic: "ٱلشُّورَىٰ", latin: "Ash-Shura", indonesia: "Asy-Syura", arti: "Musyawarah", ayat: 53, type: "Makkiyah" },
  { id: 43, arabic: "ٱلزُّخْرُف", latin: "Az-Zukhruf", indonesia: "Az-Zukhruf", arti: "Perhiasan", ayat: 89, type: "Makkiyah" },
  { id: 44, arabic: "ٱلدُّخَان", latin: "Ad-Dukhan", indonesia: "Ad-Dukhan", arti: "Kabut", ayat: 59, type: "Makkiyah" },
  { id: 45, arabic: "ٱلْجَاثِيَة", latin: "Al-Jathiyah", indonesia: "Al-Jasiyah", arti: "Yang Berlutut", ayat: 37, type: "Makkiyah" },
  { id: 46, arabic: "ٱلْأَحْقَاف", latin: "Al-Ahqaf", indonesia: "Al-Ahqaf", arti: "Bukit Pasir", ayat: 35, type: "Makkiyah" },
  { id: 47, arabic: "مُحَمَّد", latin: "Muhammad", indonesia: "Muhammad", arti: "Nabi Muhammad", ayat: 38, type: "Madaniyah" },
  { id: 48, arabic: "ٱلْفَتْح", latin: "Al-Fath", indonesia: "Al-Fath", arti: "Kemenangan", ayat: 29, type: "Madaniyah" },
  { id: 49, arabic: "ٱلْحُجُرَات", latin: "Al-Hujurat", indonesia: "Al-Hujurat", arti: "Kamar-kamar", ayat: 18, type: "Madaniyah" },
  { id: 50, arabic: "قٓ", latin: "Qaf", indonesia: "Qaf", arti: "Qaf", ayat: 45, type: "Makkiyah" },
];

// Continue with remaining surahs
export const surahNames2: SurahName[] = [
  { id: 51, arabic: "ٱلذَّارِيَات", latin: "Adh-Dhariyat", indonesia: "Az-Zariyat", arti: "Angin yang Menerbangkan", ayat: 60, type: "Makkiyah" },
  { id: 52, arabic: "ٱلطُّور", latin: "At-Tur", indonesia: "At-Tur", arti: "Bukit Tursina", ayat: 49, type: "Makkiyah" },
  { id: 53, arabic: "ٱلنَّجْم", latin: "An-Najm", indonesia: "An-Najm", arti: "Bintang", ayat: 62, type: "Makkiyah" },
  { id: 54, arabic: "ٱلْقَمَر", latin: "Al-Qamar", indonesia: "Al-Qamar", arti: "Bulan", ayat: 55, type: "Makkiyah" },
  { id: 55, arabic: "ٱلرَّحْمَٰن", latin: "Ar-Rahman", indonesia: "Ar-Rahman", arti: "Yang Maha Pengasih", ayat: 78, type: "Madaniyah" },
  { id: 56, arabic: "ٱلْوَاقِعَة", latin: "Al-Waqi'ah", indonesia: "Al-Waqi'ah", arti: "Hari Kiamat", ayat: 96, type: "Makkiyah" },
  { id: 57, arabic: "ٱلْحَدِيد", latin: "Al-Hadid", indonesia: "Al-Hadid", arti: "Besi", ayat: 29, type: "Madaniyah" },
  { id: 58, arabic: "ٱلْمُجَادِلَة", latin: "Al-Mujadilah", indonesia: "Al-Mujadalah", arti: "Wanita yang Mengajukan Gugatan", ayat: 22, type: "Madaniyah" },
  { id: 59, arabic: "ٱلْحَشْر", latin: "Al-Hashr", indonesia: "Al-Hasyr", arti: "Pengusiran", ayat: 24, type: "Madaniyah" },
  { id: 60, arabic: "ٱلْمُمْتَحَنَة", latin: "Al-Mumtahanah", indonesia: "Al-Mumtahanah", arti: "Wanita yang Diuji", ayat: 13, type: "Madaniyah" },
  { id: 61, arabic: "ٱلصَّفّ", latin: "As-Saff", indonesia: "As-Saff", arti: "Barisan", ayat: 14, type: "Madaniyah" },
  { id: 62, arabic: "ٱلْجُمُعَة", latin: "Al-Jumu'ah", indonesia: "Al-Jumu'ah", arti: "Hari Jumat", ayat: 11, type: "Madaniyah" },
  { id: 63, arabic: "ٱلْمُنَافِقُون", latin: "Al-Munafiqun", indonesia: "Al-Munafiqun", arti: "Orang-orang Munafik", ayat: 11, type: "Madaniyah" },
  { id: 64, arabic: "ٱلتَّغَابُن", latin: "At-Taghabun", indonesia: "At-Tagabun", arti: "Hari Dinampakkan Kesalahan", ayat: 18, type: "Madaniyah" },
  { id: 65, arabic: "ٱلطَّلَاق", latin: "At-Talaq", indonesia: "At-Talaq", arti: "Talak", ayat: 12, type: "Madaniyah" },
  { id: 66, arabic: "ٱلتَّحْرِيم", latin: "At-Tahrim", indonesia: "At-Tahrim", arti: "Pengharaman", ayat: 12, type: "Madaniyah" },
  { id: 67, arabic: "ٱلْمُلْك", latin: "Al-Mulk", indonesia: "Al-Mulk", arti: "Kerajaan", ayat: 30, type: "Makkiyah" },
  { id: 68, arabic: "ٱلْقَلَم", latin: "Al-Qalam", indonesia: "Al-Qalam", arti: "Pena", ayat: 52, type: "Makkiyah" },
  { id: 69, arabic: "ٱلْحَاقَّة", latin: "Al-Haqqah", indonesia: "Al-Haqqah", arti: "Hari Kiamat", ayat: 52, type: "Makkiyah" },
  { id: 70, arabic: "ٱلْمَعَارِج", latin: "Al-Ma'arij", indonesia: "Al-Ma'arij", arti: "Tempat-tempat Naik", ayat: 44, type: "Makkiyah" },
  { id: 71, arabic: "نُوح", latin: "Nuh", indonesia: "Nuh", arti: "Nabi Nuh", ayat: 28, type: "Makkiyah" },
  { id: 72, arabic: "ٱلْجِنّ", latin: "Al-Jinn", indonesia: "Al-Jin", arti: "Jin", ayat: 28, type: "Makkiyah" },
  { id: 73, arabic: "ٱلْمُزَّمِّل", latin: "Al-Muzzammil", indonesia: "Al-Muzzammil", arti: "Orang yang Berselimut", ayat: 20, type: "Makkiyah" },
  { id: 74, arabic: "ٱلْمُدَّثِّر", latin: "Al-Muddaththir", indonesia: "Al-Muddassir", arti: "Orang yang Berkemul", ayat: 56, type: "Makkiyah" },
  { id: 75, arabic: "ٱلْقِيَامَة", latin: "Al-Qiyamah", indonesia: "Al-Qiyamah", arti: "Hari Kiamat", ayat: 40, type: "Makkiyah" },
  { id: 76, arabic: "ٱلْإِنسَان", latin: "Al-Insan", indonesia: "Al-Insan", arti: "Manusia", ayat: 31, type: "Madaniyah" },
  { id: 77, arabic: "ٱلْمُرْسَلَات", latin: "Al-Mursalat", indonesia: "Al-Mursalat", arti: "Malaikat yang Diutus", ayat: 50, type: "Makkiyah" },
  { id: 78, arabic: "ٱلنَّبَأ", latin: "An-Naba", indonesia: "An-Naba'", arti: "Berita Besar", ayat: 40, type: "Makkiyah" },
  { id: 79, arabic: "ٱلنَّازِعَات", latin: "An-Nazi'at", indonesia: "An-Nazi'at", arti: "Malaikat yang Mencabut", ayat: 46, type: "Makkiyah" },
  { id: 80, arabic: "عَبَسَ", latin: "Abasa", indonesia: "'Abasa", arti: "Bermuka Masam", ayat: 42, type: "Makkiyah" },
  { id: 81, arabic: "ٱلتَّكْوِير", latin: "At-Takwir", indonesia: "At-Takwir", arti: "Menggulung", ayat: 29, type: "Makkiyah" },
  { id: 82, arabic: "ٱلْإِنفِطَار", latin: "Al-Infitar", indonesia: "Al-Infitar", arti: "Terbelah", ayat: 19, type: "Makkiyah" },
  { id: 83, arabic: "ٱلْمُطَفِّفِين", latin: "Al-Mutaffifin", indonesia: "Al-Mutaffifin", arti: "Orang-orang yang Curang", ayat: 36, type: "Makkiyah" },
  { id: 84, arabic: "ٱلْإِنشِقَاق", latin: "Al-Inshiqaq", indonesia: "Al-Insyiqaq", arti: "Terbelah", ayat: 25, type: "Makkiyah" },
  { id: 85, arabic: "ٱلْبُرُوج", latin: "Al-Buruj", indonesia: "Al-Buruj", arti: "Gugusan Bintang", ayat: 22, type: "Makkiyah" },
  { id: 86, arabic: "ٱلطَّارِق", latin: "At-Tariq", indonesia: "At-Tariq", arti: "Yang Datang di Malam Hari", ayat: 17, type: "Makkiyah" },
  { id: 87, arabic: "ٱلْأَعْلَىٰ", latin: "Al-A'la", indonesia: "Al-A'la", arti: "Yang Maha Tinggi", ayat: 19, type: "Makkiyah" },
  { id: 88, arabic: "ٱلْغَاشِيَة", latin: "Al-Ghashiyah", indonesia: "Al-Gasiyah", arti: "Hari Pembalasan", ayat: 26, type: "Makkiyah" },
  { id: 89, arabic: "ٱلْفَجْر", latin: "Al-Fajr", indonesia: "Al-Fajr", arti: "Fajar", ayat: 30, type: "Makkiyah" },
  { id: 90, arabic: "ٱلْبَلَد", latin: "Al-Balad", indonesia: "Al-Balad", arti: "Negeri", ayat: 20, type: "Makkiyah" },
  { id: 91, arabic: "ٱلشَّمْس", latin: "Ash-Shams", indonesia: "Asy-Syams", arti: "Matahari", ayat: 15, type: "Makkiyah" },
  { id: 92, arabic: "ٱلَّيْل", latin: "Al-Layl", indonesia: "Al-Lail", arti: "Malam", ayat: 21, type: "Makkiyah" },
  { id: 93, arabic: "ٱلضُّحَىٰ", latin: "Ad-Duha", indonesia: "Ad-Duha", arti: "Waktu Duha", ayat: 11, type: "Makkiyah" },
  { id: 94, arabic: "ٱلشَّرْح", latin: "Ash-Sharh", indonesia: "Al-Insyirah", arti: "Melapangkan", ayat: 8, type: "Makkiyah" },
  { id: 95, arabic: "ٱلتِّين", latin: "At-Tin", indonesia: "At-Tin", arti: "Buah Tin", ayat: 8, type: "Makkiyah" },
  { id: 96, arabic: "ٱلْعَلَق", latin: "Al-Alaq", indonesia: "Al-'Alaq", arti: "Segumpal Darah", ayat: 19, type: "Makkiyah" },
  { id: 97, arabic: "ٱلْقَدْر", latin: "Al-Qadr", indonesia: "Al-Qadr", arti: "Kemuliaan", ayat: 5, type: "Makkiyah" },
  { id: 98, arabic: "ٱلْبَيِّنَة", latin: "Al-Bayyinah", indonesia: "Al-Bayyinah", arti: "Bukti Nyata", ayat: 8, type: "Madaniyah" },
  { id: 99, arabic: "ٱلزَّلْزَلَة", latin: "Az-Zalzalah", indonesia: "Az-Zalzalah", arti: "Guncangan", ayat: 8, type: "Madaniyah" },
  { id: 100, arabic: "ٱلْعَادِيَات", latin: "Al-Adiyat", indonesia: "Al-'Adiyat", arti: "Kuda Perang yang Berlari", ayat: 11, type: "Makkiyah" },
  { id: 101, arabic: "ٱلْقَارِعَة", latin: "Al-Qari'ah", indonesia: "Al-Qari'ah", arti: "Hari Kiamat", ayat: 11, type: "Makkiyah" },
  { id: 102, arabic: "ٱلتَّكَاثُر", latin: "At-Takathur", indonesia: "At-Takasur", arti: "Bermegah-megahan", ayat: 8, type: "Makkiyah" },
  { id: 103, arabic: "ٱلْعَصْر", latin: "Al-Asr", indonesia: "Al-'Asr", arti: "Masa", ayat: 3, type: "Makkiyah" },
  { id: 104, arabic: "ٱلْهُمَزَة", latin: "Al-Humazah", indonesia: "Al-Humazah", arti: "Pengumpat", ayat: 9, type: "Makkiyah" },
  { id: 105, arabic: "ٱلْفِيل", latin: "Al-Fil", indonesia: "Al-Fil", arti: "Gajah", ayat: 5, type: "Makkiyah" },
  { id: 106, arabic: "قُرَيْش", latin: "Quraysh", indonesia: "Quraisy", arti: "Suku Quraisy", ayat: 4, type: "Makkiyah" },
  { id: 107, arabic: "ٱلْمَاعُون", latin: "Al-Ma'un", indonesia: "Al-Ma'un", arti: "Barang-barang Berguna", ayat: 7, type: "Makkiyah" },
  { id: 108, arabic: "ٱلْكَوْثَر", latin: "Al-Kawthar", indonesia: "Al-Kausar", arti: "Nikmat yang Banyak", ayat: 3, type: "Makkiyah" },
  { id: 109, arabic: "ٱلْكَافِرُون", latin: "Al-Kafirun", indonesia: "Al-Kafirun", arti: "Orang-orang Kafir", ayat: 6, type: "Makkiyah" },
  { id: 110, arabic: "ٱلنَّصْر", latin: "An-Nasr", indonesia: "An-Nasr", arti: "Pertolongan", ayat: 3, type: "Madaniyah" },
  { id: 111, arabic: "ٱلْمَسَد", latin: "Al-Masad", indonesia: "Al-Lahab", arti: "Gejolak Api", ayat: 5, type: "Makkiyah" },
  { id: 112, arabic: "ٱلْإِخْلَاص", latin: "Al-Ikhlas", indonesia: "Al-Ikhlas", arti: "Ikhlas", ayat: 4, type: "Makkiyah" },
  { id: 113, arabic: "ٱلْفَلَق", latin: "Al-Falaq", indonesia: "Al-Falaq", arti: "Waktu Subuh", ayat: 5, type: "Makkiyah" },
  { id: 114, arabic: "ٱلنَّاس", latin: "An-Nas", indonesia: "An-Nas", arti: "Manusia", ayat: 6, type: "Makkiyah" },
];

// Combine all surahs
export const allSurahNames = [...surahNames, ...surahNames2];

// Get surah by ID
export function getSurahNameById(id: number): SurahName | undefined {
  return allSurahNames.find(s => s.id === id);
}
